### PR TITLE
Add pipfile

### PR DESCRIPTION
**Pull request by janhohenheim**

### CODE REVIEW

**Review by tautropfli — CHANGES_REQUESTED** [review]
Why does `/build` and `/dist` need to be ignored?

**Comment by janhohenheim** [comment]
Do you _want_ me to commit `/build` and `/dist`? Because running `setup.py` creates those folders and it seems user unfriendly if we don't ignore them, knowing fully that they _will_ be created. You can't expect everyone to have set their global .gitignore in a specific way.

**Comment by tautropfli** [comment]
I don’t think that `setup.py` is supposed to be called directly…

**Comment by janhohenheim** [comment]
How should a user install gilderoy then, if they wish to do so?

**Comment by tautropfli** [comment]
Gilderoy can either be installed with `pip` or with `pipenv`.
For working on gilderoy itself, one can use `pip install --editable ./local/path/to/gilderoy`

**Comment by janhohenheim** [comment]
Alright, makes sense. I completely misunderstood the intend of `setup.py` then. Sorry!

**Review by tautropfli — APPROVED** [review]

**Pull request merged**
